### ISSUE TITLE
client compiled and built from source crashes

### ISSUE THREAD

**Issue by nOmi7** [haiwen/seafile-client#1078]
compiled and install jansson
compiled and install v3.1-latest libsearpc
compiled and install v6.1.6 ccnet
compiled and install v6.1.6 libseafile
compiled and install v6.1.6 seafile-client

qt5 version: 5.9.1

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 17.10
Release:	17.10
Codename:	artful

$ uname -a
Linux rogado 4.13.0-32-generic #35-Ubuntu SMP Thu Jan 25 09:13:46 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

ldd

```
ldd /opt/synktanc/desktop-linux/bin/seafile-applet             
	linux-vdso.so.1 =>  (0x00007ffe99901000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fc9e2088000)
	libcrypto.so.1.0.0 => /lib/x86_64-linux-gnu/libcrypto.so.1.0.0 (0x00007fc9e1c47000)
	libevent-2.0.so.5 => /usr/local/lib/libevent-2.0.so.5 (0x00007fc9e19fe000)
	libsqlite3.so.0 => /usr/lib/x86_64-linux-gnu/libsqlite3.so.0 (0x00007fc9e16f6000)
	libjansson.so.4 => /opt/synktanc/deps/jansson-2.11/lib/libjansson.so.4 (0x00007fc9e14e8000)
	libsearpc.so.1 => /opt/synktanc/libsearpc/lib/libsearpc.so.1 (0x00007fc9e12dd000)
	libgobject-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0 (0x00007fc9e1089000)
	libglib-2.0.so.0 => /lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007fc9e0d75000)
	libccnet.so.0 => /opt/synktanc/ccnet/lib/libccnet.so.0 (0x00007fc9e0b55000)
	libseafile.so.0 => /opt/synktanc/seafile-core/lib/libseafile.so.0 (0x00007fc9e0925000)
	libQt5Widgets.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5 (0x00007fc9e00e1000)
	libQt5Network.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Network.so.5 (0x00007fc9dfd56000)
	libQt5DBus.so.5 => /usr/lib/x86_64-linux-gnu/libQt5DBus.so.5 (0x00007fc9dfacc000)
	libQt5Gui.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5 (0x00007fc9df365000)
	libQt5Core.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Core.so.5 (0x00007fc9dec1c000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fc9de896000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fc9de67f000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fc9de29f000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fc9e284f000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fc9de09b000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fc9ddd45000)
	libffi.so.6 => /usr/lib/x86_64-linux-gnu/libffi.so.6 (0x00007fc9ddb3d000)
	libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007fc9dd8cb000)
	libuuid.so.1 => /lib/x86_64-linux-gnu/libuuid.so.1 (0x00007fc9dd6c6000)
	libz.so.1 => /usr/local/lib/libz.so.1 (0x00007fc9dd4aa000)
	libdbus-1.so.3 => /lib/x86_64-linux-gnu/libdbus-1.so.3 (0x00007fc9dd25e000)
	libGL.so.1 => /usr/lib/x86_64-linux-gnu/mesa/libGL.so.1 (0x00007fc9dcfec000)
	libpng16.so.16 => /usr/lib/x86_64-linux-gnu/libpng16.so.16 (0x00007fc9dcdba000)
	libharfbuzz.so.0 => /usr/lib/x86_64-linux-gnu/libharfbuzz.so.0 (0x00007fc9dcb26000)
	libicui18n.so.57 => /usr/lib/x86_64-linux-gnu/libicui18n.so.57 (0x00007fc9dc6b2000)
	libicuuc.so.57 => /usr/lib/x86_64-linux-gnu/libicuuc.so.57 (0x00007fc9dc30d000)
	libdouble-conversion.so.1 => /usr/lib/x86_64-linux-gnu/libdouble-conversion.so.1 (0x00007fc9dc0fc000)
	libsystemd.so.0 => /lib/x86_64-linux-gnu/libsystemd.so.0 (0x00007fc9dbe77000)
	libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007fc9dbc4c000)
	libxcb-dri3.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-dri3.so.0 (0x00007fc9dba49000)
	libxcb-present.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-present.so.0 (0x00007fc9db846000)
	libxcb-sync.so.1 => /usr/lib/x86_64-linux-gnu/libxcb-sync.so.1 (0x00007fc9db63f000)
	libxshmfence.so.1 => /usr/lib/x86_64-linux-gnu/libxshmfence.so.1 (0x00007fc9db43c000)
	libglapi.so.0 => /usr/lib/x86_64-linux-gnu/libglapi.so.0 (0x00007fc9db20c000)
	libXext.so.6 => /usr/lib/x86_64-linux-gnu/libXext.so.6 (0x00007fc9daffa000)
	libXdamage.so.1 => /usr/lib/x86_64-linux-gnu/libXdamage.so.1 (0x00007fc9dadf7000)
	libXfixes.so.3 => /usr/lib/x86_64-linux-gnu/libXfixes.so.3 (0x00007fc9dabf1000)
	libX11-xcb.so.1 => /usr/lib/x86_64-linux-gnu/libX11-xcb.so.1 (0x00007fc9da9ef000)
	libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007fc9da6b6000)
	libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007fc9da48f000)
	libxcb-glx.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-glx.so.0 (0x00007fc9da274000)
	libxcb-dri2.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-dri2.so.0 (0x00007fc9da06f000)
	libXxf86vm.so.1 => /usr/lib/x86_64-linux-gnu/libXxf86vm.so.1 (0x00007fc9d9e69000)
	libdrm.so.2 => /usr/lib/x86_64-linux-gnu/libdrm.so.2 (0x00007fc9d9c58000)
	libfreetype.so.6 => /usr/lib/x86_64-linux-gnu/libfreetype.so.6 (0x00007fc9d99a5000)
	libgraphite2.so.3 => /usr/lib/x86_64-linux-gnu/libgraphite2.so.3 (0x00007fc9d9778000)
	libicudata.so.57 => /usr/lib/x86_64-linux-gnu/libicudata.so.57 (0x00007fc9d7cfb000)
	libgcrypt.so.20 => /lib/x86_64-linux-gnu/libgcrypt.so.20 (0x00007fc9d79ed000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fc9d77e5000)
	liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007fc9d75bf000)
	liblz4.so.1 => /usr/lib/x86_64-linux-gnu/liblz4.so.1 (0x00007fc9d73a7000)
	libselinux.so.1 => /lib/x86_64-linux-gnu/libselinux.so.1 (0x00007fc9d717f000)
	libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007fc9d6f7b000)
	libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007fc9d6d75000)
	libgpg-error.so.0 => /lib/x86_64-linux-gnu/libgpg-error.so.0 (0x00007fc9d6b60000)
	libbsd.so.0 => /lib/x86_64-linux-gnu/libbsd.so.0 (0x00007fc9d694b000)
```

gdb
```
Thread 1 "seafile-applet" received signal SIGSEGV, Segmentation fault.
get_entry_for_mods (type=0x555555b42848, type=0x555555b42848, mods=0) at src/state.c:134
134	        if (entry_is_active(&type->entries[i]) &&
(gdb) bt
#0  0x00007fffe999c0b8 in get_entry_for_mods (type=0x555555b42848, type=0x555555b42848, mods=0) at src/state.c:134
#1  0x00007fffe999c0b8 in get_entry_for_key_state (group=group@entry=0, key=<optimized out>, state=<optimized out>) at src/state.c:146
#2  0x00007fffe999c537 in xkb_state_key_get_level (state=state@entry=0x555555b4f020, kc=kc@entry=10, layout=layout@entry=0) at src/state.c:164
#3  0x00007fffe999cf1a in xkb_state_key_get_syms (state=state@entry=0x555555b4f020, kc=kc@entry=10, syms_out=syms_out@entry=0x7fffffffd540)
    at src/state.c:866
#4  0x00007fffe999d4f8 in xkb_state_key_get_one_sym (state=0x555555b4f020, kc=10) at src/state.c:935
#5  0x00007fffebcda0d1 in  () at /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#6  0x00007fffebcda1c3 in  () at /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#7  0x00007fffebcdb28d in  () at /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#8  0x00007fffebcd5a1b in QXcbConnection::QXcbConnection(QXcbNativeInterface*, bool, unsigned int, char const*) ()
    at /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#9  0x00007fffebcd901a in QXcbIntegration::QXcbIntegration(QStringList const&, int&, char**) () at /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#10 0x00007fffebf9b2ab in  () at /usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqxcb.so
#11 0x00007ffff4f7bf8d in QPlatformIntegrationFactory::create(QString const&, QStringList const&, int&, char**, QString const&) ()
    at /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#12 0x00007ffff4f8c34a in QGuiApplicationPrivate::createPlatformIntegration() () at /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#13 0x00007ffff4f8ce3d in QGuiApplicationPrivate::createEventDispatcher() () at /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#14 0x00007ffff49dab85 in QCoreApplicationPrivate::init() () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#15 0x00007ffff4f8e8cf in QGuiApplicationPrivate::init() () at /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#16 0x00007ffff5d68289 in QApplicationPrivate::init() () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#17 0x00005555555fd857 in main ()

```

**Comment by nOmi7** [comment]
can someone please help or guide ?

**Comment by freeplant** [comment]
Compiling issue is beyond our range of support.
