### ISSUE TITLE
seaf-cli status fails with traceback

### ISSUE THREAD

**Issue by gschintgen** [haiwen/seafile-client#1162]
Hi,
I couldn't get seaf-cli to work as intended. It fails rather hard with some uncaught error(s):

```
root@seafcli-backup:~# mkdir seafile-client
root@seafcli-backup:~# seaf-cli init -d seafile-client
Writen seafile data directory /root/seafile-client/seafile-data to /root/.ccnet/seafile.ini
root@seafcli-backup:~# seaf-cli status
New device id created
Traceback (most recent call last):
  File "/usr/bin/seaf-cli", line 866, in <module>
    main()
  File "/usr/bin/seaf-cli", line 862, in main
    args.func(args)
  File "/usr/bin/seaf-cli", line 660, in seaf_status
    tasks = seafile_rpc.get_clone_tasks()
  File "/usr/lib/python2.7/dist-packages/pysearpc/client.py", line 110, in newfunc
    ret_str = self.call_remote_func_sync(fcall_str)
  File "/usr/lib/python2.7/dist-packages/pysearpc/named_pipe.py", line 82, in call_remote_func_sync
    self.transport.connect()
  File "/usr/lib/python2.7/dist-packages/pysearpc/named_pipe.py", line 44, in connect
    self.pipe_fd.connect(self.socket_path)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 2] No such file or directory
root@seafcli-backup:~# seaf-cli start
Starting seafile daemon ...
Started: seafile daemon ...
root@seafcli-backup:~# seaf-cli status
Traceback (most recent call last):
  File "/usr/bin/seaf-cli", line 866, in <module>
    main()
  File "/usr/bin/seaf-cli", line 862, in main
    args.func(args)
  File "/usr/bin/seaf-cli", line 660, in seaf_status
    tasks = seafile_rpc.get_clone_tasks()
  File "/usr/lib/python2.7/dist-packages/pysearpc/client.py", line 110, in newfunc
    ret_str = self.call_remote_func_sync(fcall_str)
  File "/usr/lib/python2.7/dist-packages/pysearpc/named_pipe.py", line 82, in call_remote_func_sync
    self.transport.connect()
  File "/usr/lib/python2.7/dist-packages/pysearpc/named_pipe.py", line 44, in connect
    self.pipe_fd.connect(self.socket_path)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 2] No such file or directory
```

Do note that:
- I followed the official manual (specifically: [https://help.seafile.com/en/syncing_client/linux-cli.html](https://help.seafile.com/en/syncing_client/linux-cli.html)) except for the fact that I issued `seaf-cli status` a first time before running seaf-cli start, but this should not result in a broken setup.
- The transcript above is from inside a LXD container running an unmodified basic Ubuntu 18.04 image. (I run lots of other stuff in various LXD containers without issue, so LXD should have no incidence on seaf-cli.)

I did not ask in the forums first because in my opinion this is clearly a bug: following the official documentation should not result in uncaught exceptions with python tracebacks.

Any help/workaround/fix would be much appreciated.

**Comment by gschintgen** [comment]
Oops, I noticed that `status` should only be called **after** giving a download or sync command. I'll try that now (and I'm optimistic that it will actually work), but still: a basic `status` command should always work. So for now I'm leaving this issue open.

**Comment by ukos-git** [comment]
That Info was really helpful. There should be a proper error/status message here.

**Comment by maxbeegee** [comment]
I am obtaining the same error message but with all the commands (`sync`, `download`, `download-by-name`), e.g.:

```

 $ ./seaf-cli download-by-name -s 'https://keeper.mpdl.mpg.de' -u 'USERNAME' -L 'My Library' -d ~/tmp/test
Enter password for user USERNAME:
Starting to download ...
Library a60ab260-f038-43ef-b3f4-796530c14539 will be downloaded to /afs/mpa/home/user/tmp/test
Traceback (most recent call last):
  File "/tmp/.mount_seaf-cwQVbIS/usr/lib/python3.9/site-packages/pysearpc/named_pipe.py", line 85, in _get_transport
    transport = self._pool.get(False)
  File "/afs/mpa/home/user/anaconda3/lib/python3.8/queue.py", line 167, in get
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/.mount_seaf-cwQVbIS/usr/bin/seaf-cli", line 1052, in <module>
    main()
  File "/tmp/.mount_seaf-cwQVbIS/usr/bin/seaf-cli", line 1048, in main
    args.func(args)
  File "/tmp/.mount_seaf-cwQVbIS/usr/bin/seaf-cli", line 662, in seaf_download_by_name
    seaf_download(args)
  File "/tmp/.mount_seaf-cwQVbIS/usr/bin/seaf-cli", line 601, in seaf_download
    seafile_rpc.download(repo,
  File "/tmp/.mount_seaf-cwQVbIS/usr/lib/python3.9/site-packages/pysearpc/client.py", line 125, in newfunc
    ret_str = self.call_remote_func_sync(fcall_str)
  File "/tmp/.mount_seaf-cwQVbIS/usr/lib/python3.9/site-packages/pysearpc/named_pipe.py", line 97, in call_remote_func_sync
    transport = self._get_transport()
  File "/tmp/.mount_seaf-cwQVbIS/usr/lib/python3.9/site-packages/pysearpc/named_pipe.py", line 87, in _get_transport
    transport = self._create_transport()
  File "/tmp/.mount_seaf-cwQVbIS/usr/lib/python3.9/site-packages/pysearpc/named_pipe.py", line 80, in _create_transport
    transport.connect()
  File "/tmp/.mount_seaf-cwQVbIS/usr/lib/python3.9/site-packages/pysearpc/named_pipe.py", line 44, in connect
    self.pipe.connect(self.socket_path)
FileNotFoundError: [Errno 2] No such file or directory

```

- I reinstalled seaf-cli
- I make sure the seaf-cli daemon is running (`ps aux|grep seaf` returns one process `./seaf-cli start`) 

Any ideas why this could be?

**Comment by feiniks** [comment]
> I am obtaining the same error message but with all the commands (`sync`, `download`, `download-by-name`; note: only `list-remote` is working!), e.g.:
> 
> ```
> 
>  $ ./seaf-cli download-by-name -s 'https://keeper.mpdl.mpg.de' -u 'USERNAME' -L 'My Library' -d ~/tmp/test
> Enter password for user USERNAME:
> Starting to download ...
> Library a60ab260-f038-43ef-b3f4-796530c14539 will be downloaded to /afs/mpa/home/user/tmp/test
> Traceback (most recent call last):
>   File "/tmp/.mount_seaf-cwQVbIS/usr/lib/python3.9/site-packages/pysearpc/named_pipe.py", line 85, in _get_transport
>     transport = self._pool.get(False)
>   File "/afs/mpa/home/user/anaconda3/lib/python3.8/queue.py", line 167, in get
>     raise Empty
> _queue.Empty
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/tmp/.mount_seaf-cwQVbIS/usr/bin/seaf-cli", line 1052, in <module>
>     main()
>   File "/tmp/.mount_seaf-cwQVbIS/usr/bin/seaf-cli", line 1048, in main
>     args.func(args)
>   File "/tmp/.mount_seaf-cwQVbIS/usr/bin/seaf-cli", line 662, in seaf_download_by_name
>     seaf_download(args)
>   File "/tmp/.mount_seaf-cwQVbIS/usr/bin/seaf-cli", line 601, in seaf_download
>     seafile_rpc.download(repo,
>   File "/tmp/.mount_seaf-cwQVbIS/usr/lib/python3.9/site-packages/pysearpc/client.py", line 125, in newfunc
>     ret_str = self.call_remote_func_sync(fcall_str)
>   File "/tmp/.mount_seaf-cwQVbIS/usr/lib/python3.9/site-packages/pysearpc/named_pipe.py", line 97, in call_remote_func_sync
>     transport = self._get_transport()
>   File "/tmp/.mount_seaf-cwQVbIS/usr/lib/python3.9/site-packages/pysearpc/named_pipe.py", line 87, in _get_transport
>     transport = self._create_transport()
>   File "/tmp/.mount_seaf-cwQVbIS/usr/lib/python3.9/site-packages/pysearpc/named_pipe.py", line 80, in _create_transport
>     transport.connect()
>   File "/tmp/.mount_seaf-cwQVbIS/usr/lib/python3.9/site-packages/pysearpc/named_pipe.py", line 44, in connect
>     self.pipe.connect(self.socket_path)
> FileNotFoundError: [Errno 2] No such file or directory
> ```
> 
> * I reinstalled seaf-cli
> * I make sure the seaf-cli daemon is running (`ps aux|grep seaf` returns one process `./seaf-cli start`)
> 
> Any ideas why this could be?

Hello @maxbeegee , what is your full `seaf-cli start` command? Additionally, you can check whether seaf-daemon is running by using the command `ps -ef | grep seaf-daemon`.

**Comment by maxbeegee** [comment]
Thanks for your quick reply. Then the seaf-daemon is not running as `ps aux|grep seaf` returns only one process `./seaf-cli start`

`./seaf-cli start` or `./seaf-cli start -c ~/.ccnet` is also how I (try to) start the daemon. Is there any way to see a log / verbose the client?

**Comment by feiniks** [comment]
Hello @maxbeegee, you can find the seafle.log file in the ~/.ccnet/logs directory, which should contain more detailed logs.

**Comment by maxbeegee** [comment]
Thanks!
This is the problem:

```
[03/28/25 08:48:46] seaf-daemon.c(558): starting seafile client 9.0.12
[03/28/25 08:48:46] seafile-session.c(390): client id = 6aabfaf0617b4f62cdfd65ba7cef26413376111d, client_name = unknown
[03/28/25 08:48:46] failed to bind unix socket fd to /afs/mpa/home/user/.seafile-client/seafile-data/seafile.sock : Operation not permitted
[03/28/25 08:48:46] seaf-daemon.c(583): Failed to start searpc server.
```

Any idea why this could be?

**Comment by feiniks** [comment]
Hello @maxbeegee , this issue is likely caused by initializing the seafile-data directory on a mounted hard drive, which may not support Unix sockets. You can reinitialize seaf-cli and use the -d parameter to specify the seafile-data directory to a system directory.

**Comment by maxbeegee** [comment]
Thanks, that worked! From my side you can close the comment (but I do second clearer error / warning messages as pointed out above).
