### ISSUE TITLE
seaf-cli fail with traceback, commands: download, sync

### ISSUE THREAD

**Issue by justritsu** [haiwen/seafile-client#1209]
am using CE version and am facing an issue when i use the `seaf-cli download` or `seaf-cli sync` the error resulted is 

```
Traceback (most recent call last):
  File "/usr/bin/seaf-cli", line 883, in <module>
    main()
  File "/usr/bin/seaf-cli", line 879, in main
    args.func(args)
  File "/usr/bin/seaf-cli", line 585, in seaf_sync
    repo_salt =  tmp['salt']
KeyError: 'salt'
```

even though it running good in web UI ..
if any one could help i would appreciate it.

**Comment by einer** [comment]
having the same issue here. The same client used to work and sync before, now it doesn't.
