### ISSUE TITLE
"seaf-cli sync" reports "urllib2.HTTPError: HTTP Error 500: Internal Server Error"

### ISSUE THREAD

**Issue by r4dh4l** [haiwen/seafile-client#1348]
Trying to sync a library to an existing folder via `seaf-cli` the process fails with the following error:

```
r4dh4l@vm:~$ seaf-cli sync -l b7b5749b-03c8-411a-ac37-f7da6776b871 -s https://my.ddns.net/seafile -d /home/r4dh4l/seafile/path/to/dir/
Enter username: r4dh4l@my.ddns.net
Enter password for user r4dh4l@my.ddns.net : 
Traceback (most recent call last):
  File "/usr/bin/seaf-cli", line 866, in <module>
    main()
  File "/usr/bin/seaf-cli", line 862, in main
    args.func(args)
  File "/usr/bin/seaf-cli", line 564, in seaf_sync
    token = get_token(url, username, password, tfa, conf_dir)
  File "/usr/bin/seaf-cli", line 277, in get_token
    token_json = urlopen("%s/api2/auth-token/" % url, data=data, headers=headers)
  File "/usr/bin/seaf-cli", line 210, in urlopen
    resp = urllib2.urlopen(req)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 500: Internal Server Error
r4dh4l@vm:~$
```

```
r4dh4l@vm:~$ cat .ccnet/logs/seafile.log 
[03/14/21 04:08:21] seaf-daemon.c(502): starting seafile client 6.2.11
[03/14/21 04:08:21] seafile-session.c(382): client id = ..., client_name = unknown
[03/14/21 04:08:21] seaf-daemon.c(529): rpc server started.
r4dh4l@vm:~$ 
```

I'm using the Debian10 version:

```
# apt policy seafile-cli
seafile-cli:
  Installed: 6.2.11-1
  Candidate: 6.2.11-1
  Version table:
 *** 6.2.11-1 500
        500 http://ftp.de.debian.org/debian buster/main amd64 Packages
        100 /var/lib/dpkg/status
```

The Seafile server works because I use `seaf-cli` without problems on the seafile server:

```
r4dh4l@vm-seafile:~$ seaf-cli download -l 804e0ba9-a73b-4f26-93d7-622cd55fd423 -s https://my.ddns.net/seafile -d seafile/                 
Enter username: r4dh4l@my.ddns.net
Enter password for user r4dh4l@my.ddns.net :                                                                                                                 
Starting to download ...
Library 804e0ba9-a73b-4f26-93d7-622cd55fd423 will be downloaded to /home/r4dh4l/seafile
```

Doing the same sync attempt on another server I got the reported error:

```
r4dh4l@vm-matrix:~$ seaf-cli download -l 804e0ba9-a73b-4f26-93d7-622cd55fd423 -s https://my.ddns.net/seafile -d seafile/
Enter username: r4dh4l@my.ddns.net
Enter password for user r4dh4l@my.ddns.net :
Traceback (most recent call last):
  File "/usr/bin/seaf-cli", line 866, in <module>
    main()
  File "/usr/bin/seaf-cli", line 862, in main
    args.func(args)
  File "/usr/bin/seaf-cli", line 443, in seaf_download
    token = get_token(url, username, password, tfa, conf_dir)
  File "/usr/bin/seaf-cli", line 277, in get_token
    token_json = urlopen("%s/api2/auth-token/" % url, data=data, headers=headers)
  File "/usr/bin/seaf-cli", line 210, in urlopen
    resp = urllib2.urlopen(req)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 500: Internal Server Error
```

Even `list-remote` does not work:

```
r4dh4l@vm-matrix:~$ seaf-cli list-remote -s https://my.ddns.net/seafile
Enter username: r4dh4l@my.ddns.net
Enter password for user r4dh4l@my.ddns.net : 
Traceback (most recent call last):
  File "/usr/bin/seaf-cli", line 866, in <module>
    main()
  File "/usr/bin/seaf-cli", line 862, in main
    args.func(args)
  File "/usr/bin/seaf-cli", line 387, in seaf_list_remote
    token = get_token(url, username, password, tfa, conf_dir)
  File "/usr/bin/seaf-cli", line 277, in get_token
    token_json = urlopen("%s/api2/auth-token/" % url, data=data, headers=headers)
  File "/usr/bin/seaf-cli", line 210, in urlopen
    resp = urllib2.urlopen(req)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 500: Internal Server Error
```

On the seafile server `list-remote` works fine:

```
r4dh4l@vm-seafile:~$ seaf-cli list-remote -s https://my.ddns.net/seafile
Enter username: r4dh4l@my.ddns.net
Enter password for user r4dh4l@my.ddns.net : 
Name    ID
wormhole_srv b7b5749b-03c8-411a-ac37-f7da6776b871
wormhole 7c1f4d3a-146f-4c23-81f6-9673c977c500
My Library 804e0ba9-a73b-4f26-93d7-622cd55fd423
```

Any idea what I'm doing wrong?

**Comment by killing** [comment]
You can post this issue on our forum. There should be something wrong on the server side. This is not a bug. Usage problems belongs to the forum.
