### ISSUE TITLE
Segmentation fault on KDE Plasma 5 (openSUSE Tumbleweed)

### ISSUE THREAD

**Issue by jaltek** [haiwen/seafile-client#777]
Hi,

the seafile-applet crashes on KDE / Plasma 5.

Steps:
1) start seafile-applet (through terminal)
2) right mouse-click icon and access settings (or simple click any menu item)
3) applet exits with "segmentation fault" message.

```
gdb seafile-applet 
GNU gdb (GDB; openSUSE Factory) 7.10.1
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-suse-linux".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://bugs.opensuse.org/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from seafile-applet...done.
(gdb) r
Starting program: /usr/bin/seafile-applet 
Missing separate debuginfos, use: zypper install seafile-client-debuginfo-5.0.4-0.x86_64
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[New Thread 0x7fffea3b3700 (LWP 13012)]
done
Successly create ccnet config dir /home/jaltek/.ccnet.
[New Thread 0x7fffe0971700 (LWP 13014)]
Detaching after fork from child process 13015.

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff711aca1 in QWidget::ensurePolished() const () from /usr/lib64/libQtGui.so.4
(gdb) bt
#0  0x00007ffff711aca1 in QWidget::ensurePolished() const () at /usr/lib64/libQtGui.so.4
#1  0x00007ffff711afbd in QWidget::showNormal() () at /usr/lib64/libQtGui.so.4
#2  0x00000000004d16d9 in MainWindow::showWindow() ()
#3  0x00007ffff65d0f90 in QMetaObject::activate(QObject*, QMetaObject const*, int, void**) () at /usr/lib64/libQtCore.so.4
#4  0x00007ffff7735a4e in QSystemTrayIcon::activated(QSystemTrayIcon::ActivationReason) () at /usr/lib64/libQtGui.so.4
#5  0x00007fffe999ec12 in  () at /usr/lib64/qt4/plugins/systemtrayicon/libsni-qt.so
#6  0x00007fffe99aa5ac in  () at /usr/lib64/qt4/plugins/systemtrayicon/libsni-qt.so
#7  0x00007ffff6c96205 in  () at /usr/lib64/libQtDBus.so.4
#8  0x00007ffff6c9774b in  () at /usr/lib64/libQtDBus.so.4
#9  0x00007ffff6c98437 in  () at /usr/lib64/libQtDBus.so.4
#10 0x00007ffff6c9863b in  () at /usr/lib64/libQtDBus.so.4
#11 0x00007ffff65d6ad1 in QObject::event(QEvent*) () at /usr/lib64/libQtCore.so.4
#12 0x00007ffff70caf1c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib64/libQtGui.so.4
#13 0x00007ffff70d19ec in QApplication::notify(QObject*, QEvent*) () at /usr/lib64/libQtGui.so.4
#14 0x00007ffff65bda4d in QCoreApplication::notifyInternal(QObject*, QEvent*) () at /usr/lib64/libQtCore.so.4
#15 0x00007ffff65c0e7e in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () at /usr/lib64/libQtCore.so.4
#16 0x00007ffff65ec10e in  () at /usr/lib64/libQtCore.so.4
#17 0x00007ffff515d0c7 in g_main_context_dispatch () at /usr/lib64/libglib-2.0.so.0
#18 0x00007ffff515d2f8 in  () at /usr/lib64/libglib-2.0.so.0
#19 0x00007ffff515d39c in g_main_context_iteration () at /usr/lib64/libglib-2.0.so.0
#20 0x00007ffff65ec27e in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQtCore.so.4
#21 0x00007ffff716e946 in  () at /usr/lib64/libQtGui.so.4
#22 0x00007ffff65bc411 in QEventLoop::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQtCore.so.4
#23 0x00007ffff65bc725 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQtCore.so.4
#24 0x00007ffff65c1f29 in QCoreApplication::exec() () at /usr/lib64/libQtCore.so.4
#25 0x00000000004749a3 in main ()
```

**Comment by Fly0s** [comment]
I can confirm this bug in OpenSuse Leap 42.1 and Seafile Client 5.0.4 from the home:jaltekger repository. The trigger (showing the UI) and trace are identical to jaltek. The package sni-qt and all dependencies are installed.

**Comment by jaltek** [comment]
Updated the repo to 5.0.6. Same issue...

**Comment by devillemereuil** [comment]
If it helps, I managed to get 5.0.6 to work from the DEB provided [here](https://www.seafile.com/en/download/) transformed into a RPM using the "alien" scripts. Worked for both Tumbleweed and Leap 42.1. Maybe something in the dependencies in the DEB package is missing in your package?

**Comment by jaltek** [comment]
Yes, @devillemereuil. You are right. Using the alien scripts and ignoring the ```libcrypto.so.1.0.0(OPENSSL_1.0.0)(64bit)``` dependency worked for me too (to start the GUI and applet). Maybe I'll find the missing part...

**Comment by jaltek** [comment]
I changed the spec file to build against Qt5. Now I have the same problems mentioned in #634 and #768.  
I updated the repo accordingly.

**Comment by Fly0s** [comment]
Yes, I can confirm these bugs with the updated version.

**Comment by shoeper** [comment]
https://github.com/haiwen/seafile-client/issues/634
